package utils.VariablesExport;

public class BillCsvFileUtils {
    private final static String[] columns = new String[]{
            "id entite",
            "entite",
            "date facture",
            "refacturation",
            "numero mission",
            "Expert Facture",
            "Total TTC",
            "nb prlv DI",
            "nb prlv AA",
            "pu TTC prlv",
            "total TTC prlv",
            "enrobe nb analyses",
            "enrobe val absolue pu TTC",
            "enrobe analyses prix TTC",
            "Brut HT",
            "nb analyses * pu HT",
            "Brut HT hors analyses",
            "Net HT",
            "Tiers  HT hors analyses",
            "numero Facture",
            "commercial",
            "code offre",
            "offre",
            "stratege facture",
            "mesure statique Qte",
            "mesure statique pu TTC",
            "mesure statique total TTC",
            "mesure operateur Qte",
            "mesure operateur pu TTC",
            "mesure operateur total TTC",
            "MES Qte",
            "Poseur",
            "nom utilisateur poseur",
            "prenom utilisateur poseur",
            "matricule utilisateur poseur",
            "Deposeur",
            "nom utilisateur deposeur",
            "prenom utilisateur deposeur",
            "matricule utilisateur deposeur",
            "id societe",
            "id societe prescripteur",
            "do societe",
            "do nom",
            "do prenom",
            "do adresse1",
            "do adresse2",
            "do cp",
            "do ville",
            "prescripteur societe",
            "prescripteur adresse1",
            "prescripteur adresse2",
            "prescripteur cp",
            "prescripteur ville",
            "remise",
            "proprietaire nom",
            "bien adresse1",
            "bien adresse2",
            "bien cp",
            "bien ville",
            "destination bien",
            "paiement sur place",
            "statut paiement",
            "ref client",
            "etat DI",
            "agence DI",
            "etat CO",
            "agence CO",
            "id entite region",
            "you choose",
            "code client facturation",
            "origine",
            "date envoi",
            "taux TVA",
            "Qte DAAF",
            "mesemp prix achat TTC",
            "mesemp prix TTC",
            "enrobe location nb jours",
            "enrobe location prix TTC",
            "login utilisateur enregistr",
            "nom utilisateur enregistr",
            "prenom utilisateur enregistr",
            "matricule utilisateur enregistr",
            "date mel rapport",
            "login utilisateur mel rapport",
            "nom utilisateur mel rapport",
            "prenom utilisateur mel rapport",
            "matricule utilisateur mel rapport",
            "date mission",
            "origine appel",
            "origine appel precision",
            "id mission",
            "vente add",
            "ref client",
            "CC GC",
            "id mission",
            "delais mel",
            "client factor",
            "date echeance",
            "Qte Plomb dans l'eau",
            "Qte analyse mycologique",
            "Origine Business",
            "Prescripteur",
            "prsc nom",
            "prsc adresse 1",
            "prsc adresse 2",
            "prsc CP",
            "prsc Ville",
            "prsc id"
    };

    public static String[] getColumns() {
        return columns;
    }

}
